from world.kumarpg.dicts.types_defs import types

abilities = {
    "direction sense": types["ability_dict"],
    "flight": types["ability_dict"],
    "night sight": types["ability_dict"],
    "adaptive": types["ability_dict"],
    "unnatural resistance": types["ability_dict"],
    "mana font": types["ability_dict"],
    "quick learner": types["ability_dict"],
    "waymarks": types["class_ability_dict"],
    "waymark recall": types["class_ability_dict"],
    "battle sense": types["class_ability_dict"],
    "blissful ignorance": types["class_ability_dict"],
    "sprint": types["ability_dict"],
    "dual blades": types["ability_dict"],
    "combat initiative": types["ability_dict"],
    "battle healing": types["ability_dict"],
    "battle refresher": types["ability_dict"],
    "damn healthy!": types["ability_dict"],
    "tireless": types["ability_dict"],
    "elegant egotist": types["ability_dict"],
    "acrobatic defense": types["ability_dict"],
    "berserker rage": types["ability_dict"],
    "extended weight limit": types["ability_dict"],
    "hyper combat awareness": types["ability_dict"],
    "mage sight": types["ability_dict"],
    "stealth": types["ability_dict"],
    "listening": types["ability_dict"],
    
}