from world.kumarpg.dicts.types_defs import types

spells = {
    "flashbug": types["magic_dict"],
    "shiva": types["magic_dict"],
    "counterspell": types["magic_dict"],
    "magus": types["magic_dict"],
    "hex": types["magic_dict"],
    "chaosbolt": types["magic_dict"],
    "entropy field": types["magic_dict"],
    "chaotic bombardment": types["magic_dict"],
    "mana weapon": types["magic_dict"],
    "divine judgment": types["magic_dict"],
    "raging thunderstorm": types["magic_dict"],
    "firebolt": types["magic_dict"],
    "will-o-wisp": types["magic_dict"],
    "tidal shockwave": types["magic_dict"],
    "aquabolt": types["magic_dict"],
    "bubble screen": types["magic_dict"],
    "aerobolt": types["magic_dict"],
    "windscreen": types["magic_dict"],
    "geobolt": types["magic_dict"],
    "seismic tremor": types["magic_dict"],
    "pheonix flare": types["magic_dict"],
    "voidbolt": types["magic_dict"],
    "blackhole horizon": types["magic_dict"],
    "lightbolt": types["magic_dict"],
    "gleaming aura": types["magic_dict"],
    "tornado weapon": types["magic_dict"],
    "whirlpool weapon": types["magic_dict"],
    "sandstorm weapon": types["magic_dict"],
    "phoenix weapon": types["magic_dict"],
    "blizzard weapon": types["magic_dict"],
    "shadow weapon": types["magic_dict"],
    "shockbolt": types["magic_dict"],
    "arcticbolt": types["magic_dict"],
    "air lense": types["magic_dict"],
    "snowstorm": types["magic_dict"],
    "static weapon": types["magic_dict"],
    "frozen weapon": types["magic_dict"],
    "gleaming weapon": types["magic_dict"],
    "arctic snap": types["magic_dict"],
    "earthquake": types["magic_dict"],
    "blackhole supernova": types["magic_dict"],
    "heaven's shockwave": types["magic_dict"],
    "manabolt": types["magic_dict"],
    "protection": types["magic_dict"],
    "reflection": types["magic_dict"],
    "liminal light": types["magic_dict"],
    "healing energy": types["magic_dict"],
    "haste": types["magic_dict"],
    "slow": types["magic_dict"],
    "sanctuary": types["magic_dict"],
    "gravity crush": types["magic_dict"],
    "crimson lightning": types["magic_dict"],
    "medusa's gaze": types["magic_dict"],
    "blinding light": types["magic_dict"],
    "earshock": types["magic_dict"],
    "psion wave": types["magic_dict"],
    "rebuke": types["magic_dict"],
    "attack up": types["magic_dict"],
    "defense up": types["magic_dict"],
    "armor break": types["magic_dict"],
    "power break": types["magic_dict"],
    "undine": types["magic_dict"],
    "salamander": types["magic_dict"],
    "gnome": types["magic_dict"],
    "luna": types["magic_dict"],
    "wisp": types["magic_dict"],
    "shimmer": types["magic_dict"],

}