from world.kumarpg.dicts.types_defs import types

D1_TITLES = {
    "sword master": types["title_dict"],
    "arcane archer": types["title_dict"],
    "ranger": types["title_dict"],
    "white mage": types["title_dict"],
    "black mage": types["title_dict"],
    "summoner": types["title_dict"],
    "cleric": types["title_dict"],
    "bard": types["title_dict"],
    "scout": types["title_dict"],
    "monk": types["title_dict"],
    "red mage": types["title_dict"],
    "shaman": types["title_dict"],
    "warrior": types["title_dict"],
    "knight": types["title_dict"],
    "dark knight": types["title_dict"],
    "paladin": types["title_dict"],
    "sorcerer": types["title_dict"],
    "green mage": types["title_dict"],
    "beast tamer": types["title_dict"],
    "weapon master": types["title_dict"],
    "fencer": types["title_dict"],
    "rogue": types["title_dict"],
    "armor smith": types["title_dict"],
    "weapon smith": types["title_dict"],
    "fashionista": types["title_dict"],
    "brew master": types["title_dict"],
    "cartographer": types["title_dict"],
    "battle master": types["title_dict"],
    "elementalist": types["title_dict"],
    "assassin": types["title_dict"],
    "enchanter": types["title_dict"],
    "agriculturalist": types["title_dict"],
    "harpy": types["title_dict"],
    "dragon knight": types["title_dict"],
    "primal": types["title_dict"],
    "dagger dancer": types["title_dict"],
    "mystic knight": types["title_dict"],
    "lore master": types["title_dict"],
    "wayfinder": types["title_dict"],
    "shadow dancer": types["title_dict"],
    "druid": types["title_dict"],
    "thief": types["title_dict"],
    "diplomat": types["title_dict"],
    "merchant": types["title_dict"],
    "trader": types["title_dict"],
    "warden": types["title_dict"],
    "alchemist": types["title_dict"],
    "bladesinger": types["title_dict"],
    "geomancer": types["title_dict"],
    "artificer": types["title_dict"],
    "barbarian": types["title_dict"],
    "invoker": types["title_dict"],
    "aristocrat": types["title_dict"],
    "deep wizard": types["title_dict"],
    "the deep wizard": types["title_dict"],
    "arthen champion": types["title_dict"]
    }