from world.kumarpg.dicts.types_defs import types

skills = {
    "skill": types["skill_dict"],
    "persuasion": types["skill_dict_social"],
    "haggling": types["skill_dict_social"],
    "intimidation": types["skill_dict_social"],
    "empathy": types["skill_dict_social"],
    "subterfuge": types["skill_dict_social"],
    "leadership": types["skill_dict_social"],
    "command": types["skill_dict_social"],
    "socialize": types["skill_dict_social"],
    "etiquette": types["skill_dict_social"],
    "armor smith": types["skill_dict_crafting1"],
    "weapon smith": types["skill_dict_crafting1"],
    "black smith": types["skill_dict_crafting1"],
    "jeweler": types["skill_dict_crafting1"],
    "tinkerer": types["skill_dict_crafting1"],
    "carpenter": types["skill_dict_crafting1"],
    "leather working": types["skill_dict_crafting2"],
    "seamstress": types["skill_dict_crafting2"],
    "miner": types["skill_dict_crafting3"],
    "forager": types["skill_dict_crafting3"],
    "farmer": types["skill_dict_crafting3"],
    "fisher": types["skill_dict_crafting3"],
    "scavenger": types["skill_dict_crafting3"],
    "animal husbandry": types["skill_dict_crafting3"],
    "enchanter": types["skill_dict_crafting4"],
    "scribe": types["skill_dict_crafting4"],
    "alchemy": types["skill_dict_crafting5"],
    "culinarian": types["skill_dict_crafting5"],
    "appraisal": types["skill_dict_tradesman"],
    "research": types["skill_dict_tradesman"],
    "survival": types["skill_dict_tradesman"]
}